ARG version
FROM almalinux:${almalinux:-9}
ENV course="devops"\
    duration="120hrs"
ARG trainer="sivakumar"
RUN echo "hi my course is ${course} and duration is ${duration} trainer is ${trainer}"
CMD ["sleep", "1000"]